### ISSUE TITLE
Issues after updating container

### ISSUE THREAD

**Issue by lsultana98** [ibracorp/authelia#11]
Please see screenshot of error after updating container. Any chance you're aware of this?

![image](https://user-images.githubusercontent.com/45834283/115111714-ee93c480-9fc4-11eb-8058-b94241ade345.jpeg)

**Comment by ibracorp** [comment]
Hi there! Thanks for reporting this. 

Yes, I have updated the configuration.yml in the Authelia repo. It's a copy from latest official version with changes for FreeIPA.

There's a lot of updates in it so I recommend you use it instead with your information.
