### ISSUE TITLE
Issues Using Together with VSCode (Code-Server)

### ISSUE THREAD

**Issue by norsemangrey** [ibracorp/authelia#12]
I have got the setup working with most of my services, but for some reason when trying to get it to work with VSCode (using linuxserver/code-server) I only get a white/blank screen after login. I get redirected to the correct address after successful authentication. Any tip as to what might be wrong? I am using the same endpoint configuration for all the services just changing out the address and port number. I have no trouble with VSCode when not behind Authelia. Checking F12 on the page shows a bunch of WebSocte error like this:

WebSocket connection to 'wss://vscode.domain.no/?type=Management&reconnectionToken=d0bb10e8-2249-4f90-9da8-2b4358f90451&reconnection=false&skipWebSocketFrames=false' failed:

**Comment by bjun626** [comment]
Try changing this in the NPM code-server proxy host advance option,
```diff
- set $upstream_codes-erver $forward_scheme://$server:$port;
- proxy_pass $upstream_code-server;
+ set $upstream_codeserver $forward_scheme://$server:$port;
+ proxy_pass $upstream_codeserver;
```

**Comment by ibracorp-sycotix** [comment]
Solution provided
