### ISSUE TITLE
Configuration file permissions

### ISSUE THREAD

**Issue by sgraaf** [ibracorp/authelia#6]
Hi there!

I was happily following along with your in-depth tutorial on installing Authelia, right up until where you edit the configuration file (right around the 15 minute mark in the video). When I try to open the freshly created configuration.yml file, I am confronted with a file permissions-related error: 
![file permissions error](https://i.imgur.com/rWR9ZPU.png)

When I check the file permissions, my suspicions are quickly confirmed:
```bash
root@Alexandria:~# ls -lah /mnt/user/appdata/Authelia/
total 20K
drwxrwxrwx 1 nobody users  34 Mar  5 17:20 ./
drwxrwxrwx 1 nobody users 410 Mar  5 17:19 ../
-rw------- 1 nobody users 20K Mar  5 17:20 configuration.yml
```

After modifying the file permissions, I managed to resolve the issue:
```bash
root@Alexandria:~# chmod a+rw /mnt/user/appdata/Authelia/configuration.yml 
root@Alexandria:~# ls -lah /mnt/user/appdata/Authelia/
total 20K
drwxrwxrwx 1 nobody users  34 Mar  5 17:20 ./
drwxrwxrwx 1 nobody users 410 Mar  5 17:19 ../
-rw-rw-rw- 1 nobody users 20K Mar  5 17:20 configuration.yml
```

This all to say: while I managed to resolve the issue quickly and easily, it did surprise me, and might prove troublesome to people that are less experienced with Unix-based operating systems. As such, it might prove worthwhile to look into this matter.

**Comment by ibracorp** [comment]
Thank you for taking the time to report this. I will add this to the FAQ section to help others. 

Cheers!
