### ISSUE TITLE
question endpoint conf

### ISSUE THREAD

**Issue by repomanz** [ibracorp/authelia#7]
Hello - 

I'm putting the finishing touches based on your guide.  I have a question about the endpoint protection conf file.
I'm running home assistant on a VM (not on unraid's docker), what edits would I need to do to the upstream_CONTAINERNAME rows to enable this?

Also, what is this: 
set_real_ip_from 192.168.1.0/16;

FYI: subbed your channel today on youtube. great content. Thanks for putting together.

**Comment by repomanz** [comment]
quick update: I just put in CONTAINERNAME as homeassistant.  
This appears to work fine in chrome but not firefox. maybe something related to a plugin I have installed.

**Comment by ibracorp** [comment]
> quick update: I just put in CONTAINERNAME as homeassistant.  
> This appears to work fine in chrome but not firefox. maybe something related to a plugin I have installed.

Hi mate, firstly would like to thank you for taking the time to log your suggestions and feedback. Appreciate it. 

I will have some time later to sit down and work through them, in the meantime send me any updates. 

Thanks again for your support!

**Comment by mitchross** [comment]
I would like to know how to do this also. I want to use a direct ip/port instead of a container name,
