### ISSUE TITLE
documenation request: cloudflare / hardening of authelia with certs and nginx proxy manager

### ISSUE THREAD

**Issue by repomanz** [ibracorp/authelia#8]
Hello - 

I have my cloudflare ssl settings to full strict.

In your current guide I don't see a mention in the nginx proxy manager from proxy to authelia via https.  That means authentication requests going from proxy to authelia are over http, not https, over internal network.  When you get a moment could you update your guide on these points (if you agree).  Maybe an optional section for further hardening for those of us wanting full end to end encryption.

- cloudflare users get their cert origin keys
- configure authelia to use the key/cert lines
- configure nginx proxy manager to use https (instead of http)
- updating of the endpoint and authelia conf files used in nginx proxy manager advanced settings.

**Comment by repomanz** [comment]
to help mitigate risks with authelia / npm, non-cloudflare drive by traffic on my IP address I am only allowing traffic from cloudflare's published networks using pfsense and pfblockerng.

cloudflare ip4 lists here:
https://www.cloudflare.com/ips-v4

![image](https://user-images.githubusercontent.com/20090451/111792948-c2d0d200-8892-11eb-9da2-9e3df9b33368.png)

**Comment by ibracorp** [comment]
Excellent points! This is certainly valuable to the community and I will update it shortly to reflect your suggestions

**Comment by MalMcWil** [comment]
Another idea for optional configs, users might benefit from tips on cloudflare firewall rules as well. My home ip changes but it's simple enough to update in cloudflare. I created two rules to filter cloudflare to only allow my home and VPN ip. 

Allow rule
(ip.src eq <homeip>) or (ip.src eq <vpnip>)
Then action allow

Deny Rule
(ip.src ne <homeip>) or (ip.src ne <vpnip>)
Then action deny

Not sure if I need the redundant rules but it can't hurt.

**Comment by ibracorp-sycotix** [comment]
Improvements noted. Updates will be made on the new docs site: https://docs.ibracorp.io
