### ISSUE TITLE
Issues with browser cache and Authelia/NginxProxyManager

### ISSUE THREAD

**Issue by evakq8r** [ibracorp/authelia#9]
Hi,

I'm having issues with Authelia allowing browsing to the proxied address after authentication has been successful once.

I have Authelia and NginxProxyManager setup on Unraid (6.9.1), using Brave as my main browser (have also tested Edge, albeit U2F doesn't work with Edge). Once I have authenticated (either with U2F or OTP) once, it will bring me to where I wanted to go. If I try to navigate to a different reverse proxy address protected by Authelia in a different tab, it appears to remember the cache of the previous authentication and will not go any further than the below:

![image](https://user-images.githubusercontent.com/14250328/112101820-36f2d900-8bf7-11eb-8950-f36181db18ce.png)

I have tried Incognito mode and the same behaviour is experienced; authenticates once, but successive attempts retain the previous successful auth but do not navigate to the address I was looking to go to.

I'm using the Protected Endpoint.conf file provided as part of the setup guide and have the placeholders replaced with my information, but am just wondering whether this is expected behaviour?

**Comment by Davrizio** [comment]
I am having the exact same issue! Any luck figuring it out?

**Comment by ibracorp-sycotix** [comment]
What do your Authelia logs say?

**Comment by evakq8r** [comment]
@ibracorp-sycotix Given this was ~3 months ago, unfortunately the testing, setup and environment has changed.

I'm no longer able to reliably replace this issue as I've found some of the endpoints protected, Authelia seems to mess with (ie. I authenticate 2FA in Authelia, then when it redirects to the endpoint Authelia will either cause the endpoint not to load or it will login loop). Removing the endpoint config from NPM makes this issue disappear entirely.

I'll open a new ticket if I experience the same problems again. @Davrizio, I'd suggest opening a new ticket also.
